### ISSUE TITLE
Changing  UI Scale messes up aligment of some display settings

### ISSUE THREAD

**Issue by aaceace** [baharms/enemybar2#1]
I changed the UI Scale to 1.2 since I play at a high resolution and now the Action Name section distance section aren't where they are supposed to be.  
![ss+(2020-03-25+at+03 56 59)](https://user-images.githubusercontent.com/62108169/77584735-530f4d80-6eb1-11ea-8aa7-e7cd2234d0a2.jpg)

**Comment by AkadenTK** [comment]
Hey thanks! I've submitted a fix for this issue.
