### ISSUE TITLE
Possible to add self casting bar?

### ISSUE THREAD

**Issue by neon-rage** [baharms/enemybar2#2]
Love the addon, one question is would it be possible to add a new "bar"? One that could be dragged around and show self casting actions? Would be nice to have a movable bar that at the very least showed you are in the middle of casting something and what that something is. A bonus would be to somehow calculate the cast time and display it as a progress bar (not sure how feasible that is with FFXI).

**Comment by AkadenTK** [comment]
I did consider it, but there's currently an addon in development that has a casting animation :).

Maybe sometime later if that addon never manfests itself or if I want to include it in for stylistic reason. But not just now.

**Comment by neon-rage** [comment]
Out of curiosity, what addon in development are you referring to?
