### ISSUE TITLE
Target Bar Debuff Issue

### ISSUE THREAD

**Issue by eyeshark** [baharms/enemybar2#3]
I have noticed that even if I use the command to enable debuffs to show on the target bar (command goes through and responds with an echo that it's turned on), I don't see any debuff indicators on the target bar. Neither through normal play or while setup mode is enabled.

**Comment by AkadenTK** [comment]
I'll need more information, as debuffs/buffs in game are very differently tracked depending on the target.

Enemies' debuffs are tracked through the action packet, and only a few are actively tracked.
Party members' debuffs are tracked much more accurately though the party member buffs packet sent to the client.
Local Player buffs are tracked through the player buffs packet sent to the client.

**Comment by eyeshark** [comment]
I am specifically referring to mob debuffs.
i.e. when targetting a mob I am fighting, I don't see any debuffs. I suppose, as you mentioned, that's just sort of hit and miss?

**Comment by AkadenTK** [comment]
Very hit and miss. And probably easily broken with an update from SE. I wouldn't rely on it anyway as the server state of the enemy's buffs is never sent to the user. EnemyBar2 basically has to infer that a debuff was applied, and won't know for sure if/when the debuff is removed.

**Comment by eyeshark** [comment]
Thank you for the response!
